language: node_js
node_js:
  - "7"

before_install:
  - npm install -g npm@latest
  - npm install -g ionic cordova

install:
  - npm install

script:
  - ionic cordova build ios
  - ionic cordova build android
