os:
  - osx

language: node_js
node_js:
  - "7"

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25

before_install:
  - export ANDROID_HOME=~/Library/Android/sdk
  - npm install -g ionic cordova

install:
  - npm install

script:
  - ionic cordova build ios
  - ionic cordova build android
