language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g cordova
  - npm install -g ionic

# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start

script:
  - ionic build ios
  # - npm run test-travis
