language: node_js
node_js:
  - "0.12"

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g bower
  - npm install -g cordova
  - npm install -g ionic
  - bower install

script:
  - ionic build ios
